/**
 * Structured content generated by AI, mapped to scaffold template tokens.
 */
export interface AIGeneratedContent {
  productVision: string;
  problemStatement: string;
  successCriteria: string;
  valueProposition: string;
  outOfScope: string;
  /** Formatted markdown with epic definitions. */
  epics: string;
  /** Formatted markdown with task slice definitions. */
  starterTasks: string;
  /** Definition of Done checklist. */
  definitionOfDone: string;
}

/**
 * Result of validating AI-generated content.
 */
export interface ValidationResult {
  valid: boolean;
  warnings: string[];
}

/**
 * Error thrown when the AI output cannot be parsed at all.
 */
export class AIParseError extends Error {
  /** The raw unparseable output for debugging. */
  readonly rawOutput: string;

  constructor(rawOutput: string) {
    super("AI output is unparseable -- no section markers found");
    this.name = "AIParseError";
    this.rawOutput = rawOutput;
  }
}

/**
 * Section names used as delimiters in the AI output.
 */
const SECTION_NAMES = [
  "PRODUCT_VISION",
  "PROBLEM_STATEMENT",
  "SUCCESS_CRITERIA",
  "VALUE_PROPOSITION",
  "OUT_OF_SCOPE",
  "EPICS",
  "STARTER_TASKS",
  "DEFINITION_OF_DONE",
] as const;

type SectionName = (typeof SECTION_NAMES)[number];

/**
 * Default fallback value used when a section is missing from the AI output.
 */
const FALLBACK_VALUE = "To be defined by @meto-pm";

/**
 * Maps section names to AIGeneratedContent field keys.
 */
const SECTION_TO_FIELD: Record<SectionName, keyof AIGeneratedContent> = {
  PRODUCT_VISION: "productVision",
  PROBLEM_STATEMENT: "problemStatement",
  SUCCESS_CRITERIA: "successCriteria",
  VALUE_PROPOSITION: "valueProposition",
  OUT_OF_SCOPE: "outOfScope",
  EPICS: "epics",
  STARTER_TASKS: "starterTasks",
  DEFINITION_OF_DONE: "definitionOfDone",
};

/**
 * Extracts the content between section markers for a given section name.
 * Returns undefined if the section is not found.
 */
function extractSection(raw: string, sectionName: SectionName): string | undefined {
  const startMarker = `---SECTION:${sectionName}---`;
  const endMarker = `---END:${sectionName}---`;

  const startIndex = raw.indexOf(startMarker);
  if (startIndex === -1) {
    return undefined;
  }

  const contentStart = startIndex + startMarker.length;
  const endIndex = raw.indexOf(endMarker, contentStart);
  if (endIndex === -1) {
    return undefined;
  }

  return raw.slice(contentStart, endIndex).trim();
}

/**
 * Parses raw AI output into structured AIGeneratedContent.
 *
 * Extracts content between section markers (`---SECTION:<NAME>---` / `---END:<NAME>---`).
 * Missing sections receive a fallback value. If no markers are found at all,
 * throws an AIParseError.
 *
 * @param raw - The raw stdout string from the Claude Code subprocess
 * @returns Parsed and structured content ready for template token mapping
 * @throws {AIParseError} If the output contains no recognizable section markers
 */
export function parseAIOutput(raw: string): AIGeneratedContent {
  let foundSections = 0;

  const result: AIGeneratedContent = {
    productVision: FALLBACK_VALUE,
    problemStatement: FALLBACK_VALUE,
    successCriteria: FALLBACK_VALUE,
    valueProposition: FALLBACK_VALUE,
    outOfScope: FALLBACK_VALUE,
    epics: FALLBACK_VALUE,
    starterTasks: FALLBACK_VALUE,
    definitionOfDone: FALLBACK_VALUE,
  };

  for (const sectionName of SECTION_NAMES) {
    const content = extractSection(raw, sectionName);
    if (content !== undefined) {
      foundSections++;
      const fieldKey = SECTION_TO_FIELD[sectionName];
      result[fieldKey] = content.length > 0 ? content : FALLBACK_VALUE;
    }
  }

  if (foundSections === 0) {
    throw new AIParseError(raw);
  }

  return result;
}

/**
 * Validates parsed AI-generated content for structural quality.
 *
 * Checks:
 * - No section is empty or still using the fallback value
 * - Epics section contains at least `## E1`
 * - Starter tasks section contains at least `## [slice-001]`
 * - Each task has "Acceptance Criteria" and "Out of Scope" headings
 *
 * @param content - The parsed AIGeneratedContent to validate
 * @returns A ValidationResult indicating whether the content is valid, with warnings
 */
export function validateAIContent(content: AIGeneratedContent): ValidationResult {
  const warnings: string[] = [];

  const fieldLabels: Record<keyof AIGeneratedContent, string> = {
    productVision: "Product Vision",
    problemStatement: "Problem Statement",
    successCriteria: "Success Criteria",
    valueProposition: "Value Proposition",
    outOfScope: "Out of Scope",
    epics: "Epics",
    starterTasks: "Starter Tasks",
    definitionOfDone: "Definition of Done",
  };

  for (const [key, label] of Object.entries(fieldLabels)) {
    const value = content[key as keyof AIGeneratedContent];
    if (value.length === 0 || value === FALLBACK_VALUE) {
      warnings.push(`${label} section is missing or uses fallback value`);
    }
  }

  if (!content.epics.includes("## E1")) {
    warnings.push("Epics section does not contain at least ## E1");
  }

  if (!content.starterTasks.includes("## [slice-001]")) {
    warnings.push("Starter Tasks section does not contain at least ## [slice-001]");
  }

  if (content.starterTasks !== FALLBACK_VALUE) {
    if (!content.starterTasks.includes("Acceptance Criteria")) {
      warnings.push("Starter Tasks are missing Acceptance Criteria headings");
    }
    if (!content.starterTasks.includes("Out of Scope")) {
      warnings.push("Starter Tasks are missing Out of Scope headings");
    }
  }

  return {
    valid: warnings.length === 0,
    warnings,
  };
}
